#extensions
dot pie: ".py"
dot talon: ".talon"
dot mark down: ".md"
dot shell: ".sh"
dot vim: ".vim"
dot see: ".c"
dot see sharp: ".cs"
dot com: ".com"
dot net: ".net"
dot org: ".org"
dot exe: ".exe"
dot JS: ".js"
dot HTML: ".html"
dot CSS: ".css"
dot (bin | bend): ".bin"	
dot (jason | jay son): ".json"